services:
  pg:
    image: bitnami/postgresql:latest
    container_name: postgres-cashkit
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockerW
      - POSTGRES_DB=cashkit
    volumes:
      - ./data/postgres:/bitnami/postgresql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-cashkit
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: cashkit-api
    ports:
      - "1010:1010"
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
