version: "3.9"

services:
  api:
    container_name: cashkit-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
