version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-cashkit
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cashkit
    volumes:
      - pg_data:/bitnami/postgresql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-cashkit
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
